# Generated by Django 5.2.3 on 2025-07-02 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('PG', 'PREMIUM GOLD'), ('ML', 'MASALA'), ('GR', 'GINGER'), ('PL', 'PLAIN'), ('EL', 'ELAICHIE')], max_length=2)),
            ],
        ),
    ]
